# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/data_memory_internal/data_memory_internal.xci
# IP: The module: 'data_memory_internal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/data_memory_internal/data_memory_internal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory_internal'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/data_memory_internal/data_memory_internal.xci
# IP: The module: 'data_memory_internal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/data_memory_internal/data_memory_internal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory_internal'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
