# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust.xci
# IP: The module: 'clk_adjust' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_adjust'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_adjust'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_adjust'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust.xci
# IP: The module: 'clk_adjust' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_adjust'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_adjust'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/projects/sustech/computer_organization/labs/cpu/cpu.srcs/sources_1/ip/clk_adjust/clk_adjust_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_adjust'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
