# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/uart/uart.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: ip/clk_adjust/clk_adjust.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_adjust || ORIG_REF_NAME==clk_adjust} -quiet] -quiet
