# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint_cpu.xdc

# IP: ip/uart/uart.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet
