webtalk_init -webtalk_dir D:/projects/sustech/computer_organization/labs/cpu/cpu.sim/sim_1/behav/xsim/xsim.dir/board_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun  3 03:27:40 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "26443098-474d-4cca-8adc-bfdc7376222a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3b64523f8d9b41669b6cffba67a1e652" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "57" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "29 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 35855709 -regid "" -xml D:/projects/sustech/computer_organization/labs/cpu/cpu.sim/sim_1/behav/xsim/xsim.dir/board_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/projects/sustech/computer_organization/labs/cpu/cpu.sim/sim_1/behav/xsim/xsim.dir/board_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/projects/sustech/computer_organization/labs/cpu/cpu.sim/sim_1/behav/xsim/xsim.dir/board_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
